//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Expense.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseItem
    {
        public int ID { get; set; }
        public int ExpenseId { get; set; }
        public string ExpenseDescription { get; set; }
        public decimal ExpenseAmount { get; set; }
        public System.DateTime ExpenseDate { get; set; }
    
        public virtual Expense Expense { get; set; }
    }
}
